import { storage } from "./storage";
import { log } from "./index";

const PARKS_DATA = [
  { name: "Acadia", state: "Maine", description: "Covering most of Mount Desert Island and other coastal islands, Acadia features the tallest mountain on the Atlantic coast, granite peaks, ocean shoreline, woodlands, and lakes.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Bass_Harbor_Lighthouse_b.jpg/400px-Bass_Harbor_Lighthouse_b.jpg" },
  { name: "American Samoa", state: "American Samoa", description: "The southernmost national park protects coral reefs, tropical rainforests, volcanic mountains, and white beaches across three Samoan islands.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Ofu_Beach_American_Samoa_US_National_Park_Service.jpg/400px-Ofu_Beach_American_Samoa_US_National_Park_Service.jpg" },
  { name: "Arches", state: "Utah", description: "Home to over 2,000 natural sandstone arches including the famous Delicate Arch, with pinnacles, balanced rocks, and sandstone fins.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Delicate_Arch_sunset.jpg/400px-Delicate_Arch_sunset.jpg" },
  { name: "Badlands", state: "South Dakota", description: "Dramatic landscapes of sharply eroded buttes and pinnacles amid the largest undisturbed mixed grass prairie in the United States.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/MK00609_Badlands.jpg/400px-MK00609_Badlands.jpg" },
  { name: "Big Bend", state: "Texas", description: "Along the Rio Grande river on the US-Mexico border, this park includes the entire Chisos mountain range and a large swath of Chihuahuan Desert.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/On_the_Border_%2839960085292%29.jpg/400px-On_the_Border_%2839960085292%29.jpg" },
  { name: "Biscayne", state: "Florida", description: "The majority of this park is water, protecting the northernmost Florida Keys coral reef and offering pristine snorkeling and diving.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Biscayne_underwater_NPS1.jpg/400px-Biscayne_underwater_NPS1.jpg" },
  { name: "Black Canyon of the Gunnison", state: "Colorado", description: "The Gunnison River carved this deep, dramatic canyon through Precambrian rock, creating some of the steepest cliffs and oldest exposed rock in North America.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Black_canyon_gunnison_Colorado.jpg/400px-Black_canyon_gunnison_Colorado.jpg" },
  { name: "Bryce Canyon", state: "Utah", description: "Famous for its crimson-colored hoodoos—tall, thin rock spires—Bryce features the largest collection of hoodoos in the world within a series of natural amphitheaters.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Inspiration_Point_Bryce_Canyon_November_2018_panorama.jpg/400px-Inspiration_Point_Bryce_Canyon_November_2018_panorama.jpg" },
  { name: "Canyonlands", state: "Utah", description: "Carved by the Colorado and Green Rivers, this landscape of canyons, mesas, and buttes is divided into four districts showcasing millions of years of erosion.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Ekker_Butte_from_Green_River_Overlook.jpg/400px-Ekker_Butte_from_Green_River_Overlook.jpg" },
  { name: "Capitol Reef", state: "Utah", description: "A 100-mile long wrinkle in the earth's crust called the Waterpocket Fold, featuring colorful canyons, ridges, buttes, and monoliths.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Capitol_Reef_National_Park.jpg/400px-Capitol_Reef_National_Park.jpg" },
  { name: "Carlsbad Caverns", state: "New Mexico", description: "A UNESCO World Heritage Site featuring over 119 caves formed when sulfuric acid dissolved limestone, including the Big Room—one of the largest underground chambers in North America.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Carlsbad_Interior_Formations.jpg/400px-Carlsbad_Interior_Formations.jpg" },
  { name: "Channel Islands", state: "California", description: "Five of the eight Channel Islands are protected, with their isolated ecosystems home to unique animal species, rich kelp forests, and over 2,000 plant and animal species.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Santa_Cruz_Island_CA_DSC_4323_ad.JPG/400px-Santa_Cruz_Island_CA_DSC_4323_ad.JPG" },
  { name: "Congaree", state: "South Carolina", description: "The largest intact expanse of old-growth bottomland hardwood forest in the southeastern US, home to champion trees and a stunning diversity of plant and animal species.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Baldcypress_%28Taxodium_distichum%29_on_Congaree_National_Park_Low_Boardwalk_trail.jpg/400px-Baldcypress_%28Taxodium_distichum%29_on_Congaree_National_Park_Low_Boardwalk_trail.jpg" },
  { name: "Crater Lake", state: "Oregon", description: "Crater Lake, formed by the collapse of Mount Mazama volcano, is the deepest lake in the US and one of the most pristine, known for its vivid blue color.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Aerial_Crater_Lake_%28cropped%29.jpg/400px-Aerial_Crater_Lake_%28cropped%29.jpg" },
  { name: "Cuyahoga Valley", state: "Ohio", description: "Along the Cuyahoga River between Akron and Cleveland, this park preserves rural landscapes, including farmsteads, trails, and the Ohio & Erie Canal.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Cuyahoga_Valley_National_Park_20.jpg/400px-Cuyahoga_Valley_National_Park_20.jpg" },
  { name: "Death Valley", state: "California/Nevada", description: "The hottest, driest, and lowest national park containing Badwater Basin at 282 feet below sea level, alongside snow-capped peaks, colorful canyons, and vast sand dunes.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Isolated_Desert.jpg/400px-Isolated_Desert.jpg" },
  { name: "Denali", state: "Alaska", description: "Home to Denali (Mount McKinley), the highest peak in North America at 20,310 feet, surrounded by pristine subarctic wilderness, glaciers, and abundant wildlife.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Wonder_Lake_and_Denali.jpg/400px-Wonder_Lake_and_Denali.jpg" },
  { name: "Dry Tortugas", state: "Florida", description: "A remote cluster of islands west of Key West, featuring historic Fort Jefferson, vibrant coral reefs, and pristine tropical waters accessible only by boat or seaplane.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Fort-Jefferson_Dry-Tortugas.jpg/400px-Fort-Jefferson_Dry-Tortugas.jpg" },
  { name: "Everglades", state: "Florida", description: "The largest tropical wilderness in the US, protecting a vast network of wetlands and forests fed by the Kissimmee River, home to 36 threatened or protected species.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Sunset_over_the_River_of_Grass%2C_NPSphoto%2C_G.Gardner_%289255157507%29.jpg/400px-Sunset_over_the_River_of_Grass%2C_NPSphoto%2C_G.Gardner_%289255157507%29.jpg" },
  { name: "Gates of the Arctic", state: "Alaska", description: "The northernmost national park, entirely above the Arctic Circle, features pristine wilderness with no roads, trails, or facilities—a true frontier of wild Alaska.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Remote_river_in_Gates_of_the_Arctic_%2816524035298%29.jpg/400px-Remote_river_in_Gates_of_the_Arctic_%2816524035298%29.jpg" },
  { name: "Gateway Arch", state: "Missouri", description: "The smallest national park commemorates the westward expansion with the iconic 630-foot stainless steel Gateway Arch designed by Eero Saarinen.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/St_Louis_night_expblend.jpg/400px-St_Louis_night_expblend.jpg" },
  { name: "Glacier", state: "Montana", description: "A pristine wilderness of alpine meadows, turquoise lakes, and ancient glaciers set among the Northern Rocky Mountains with over 700 miles of trails.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Mountain_Goat_at_Hidden_Lake.jpg/400px-Mountain_Goat_at_Hidden_Lake.jpg" },
  { name: "Glacier Bay", state: "Alaska", description: "A dramatic landscape of tidewater glaciers, snow-capped mountain ranges, ocean coastline, deep fjords, and freshwater lakes in Southeast Alaska.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Glacier_Bay_National_Park%2C_July_28%2C_2012.jpg/400px-Glacier_Bay_National_Park%2C_July_28%2C_2012.jpg" },
  { name: "Grand Canyon", state: "Arizona", description: "A steep-sided canyon carved by the Colorado River, revealing nearly 2 billion years of geological history in its layered bands of colorful rock stretching 277 miles.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Dawn_on_the_S_rim_of_the_Grand_Canyon_%288645178272%29.jpg/400px-Dawn_on_the_S_rim_of_the_Grand_Canyon_%288645178272%29.jpg" },
  { name: "Grand Teton", state: "Wyoming", description: "The dramatic Teton Range rises abruptly 7,000 feet above the valley floor of Jackson Hole, with pristine alpine lakes, old-growth forests, and abundant wildlife.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Barns_grand_tetons.jpg/400px-Barns_grand_tetons.jpg" },
  { name: "Great Basin", state: "Nevada", description: "Features 5,000-year-old bristlecone pines, the Lehman Caves marble cavern, Wheeler Peak glacier, and some of the darkest night skies in the country.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Upper_Lehman_Creek.jpg/400px-Upper_Lehman_Creek.jpg" },
  { name: "Great Sand Dunes", state: "Colorado", description: "Home to the tallest sand dunes in North America, up to 750 feet, set against the Sangre de Cristo Mountains, with diverse habitats from alpine lakes to grasslands.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Sun_and_Shadow_Patterns_on_Dunes_%2828471118064%29.jpg/400px-Sun_and_Shadow_Patterns_on_Dunes_%2828471118064%29.jpg" },
  { name: "Great Smoky Mountains", state: "Tennessee/North Carolina", description: "America's most-visited national park, famous for its misty mountain ridges, ancient mountains, diverse plant life, and rich Southern Appalachian cultural heritage.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Foothills_Parkway%2C_November_2018--Joye_Ardyn_Durham_%2831031302587%29.jpg/400px-Foothills_Parkway%2C_November_2018--Joye_Ardyn_Durham_%2831031302587%29.jpg" },
  { name: "Guadalupe Mountains", state: "Texas", description: "Home to Guadalupe Peak, the highest point in Texas, and El Capitan, a massive limestone cliff, with extensive Permian fossil reef and diverse Chihuahuan Desert landscapes.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Guadalupe_Peak_from_Hunter_Peak.jpg/400px-Guadalupe_Peak_from_Hunter_Peak.jpg" },
  { name: "Haleakala", state: "Hawaii", description: "Named after the massive Haleakala shield volcano, this park features a stunning 10,023-foot summit, rare silversword plants, and some of the darkest skies on Earth.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Haleakala_National_Park_02.jpg/400px-Haleakala_National_Park_02.jpg" },
  { name: "Hawaii Volcanoes", state: "Hawaii", description: "Home to two of the world's most active volcanoes—Kilauea and Mauna Loa—this park showcases 70 million years of volcanic activity, from sea level to 13,681 feet.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Sulfur_dioxide_emissions_from_the_Halemaumau_vent_04-08-1_1.jpg/400px-Sulfur_dioxide_emissions_from_the_Halemaumau_vent_04-08-1_1.jpg" },
  { name: "Hot Springs", state: "Arkansas", description: "The oldest area in the national park system, protecting 47 natural thermal springs flowing from Hot Springs Mountain, surrounded by historic Bathhouse Row.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Steamy_Entrance_Springs_on_Cold_Night_in_Hot_Springs_National_Park.jpg/400px-Steamy_Entrance_Springs_on_Cold_Night_in_Hot_Springs_National_Park.jpg" },
  { name: "Indiana Dunes", state: "Indiana", description: "Over 15 miles of Lake Michigan shoreline with towering sand dunes up to 200 feet, diverse habitats from bogs to prairies, and over 1,100 native plant species.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/2010-11-26_3060x2040_portage_indiana_dunes.jpg/400px-2010-11-26_3060x2040_portage_indiana_dunes.jpg" },
  { name: "Isle Royale", state: "Michigan", description: "A remote island archipelago in Lake Superior, featuring pristine boreal forests, wolves, moose, and a long history of copper mining accessible only by boat or seaplane.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/IsleRoyalePlane.jpg/400px-IsleRoyalePlane.jpg" },
  { name: "Joshua Tree", state: "California", description: "Where the Mojave and Colorado deserts meet, featuring iconic twisted Joshua trees, massive boulder formations, and some of the best stargazing in southern California.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Joshua_Tree_-_Rock_formation_in_Real_Hidden_Valley_1.jpg/400px-Joshua_Tree_-_Rock_formation_in_Real_Hidden_Valley_1.jpg" },
  { name: "Katmai", state: "Alaska", description: "Famous for its brown bears fishing for salmon at Brooks Falls, this park also features the Valley of Ten Thousand Smokes, formed by the 1912 Novarupta eruption.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Grizzly_mama_bear_with_spring_cubs._Naknek_Lake%2C_Katmai_National_Park%2C_Alaska.jpg/400px-Grizzly_mama_bear_with_spring_cubs._Naknek_Lake%2C_Katmai_National_Park%2C_Alaska.jpg" },
  { name: "Kenai Fjords", state: "Alaska", description: "Home to the Harding Icefield, one of the largest ice fields in the US, with nearly 40 glaciers flowing from its edges into dramatic fjords teeming with marine wildlife.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/KENAI_FJORDS_NATIONAL_PARK%2C_ALASKA_--_NORTHWEST_GLACIER.jpg/400px-KENAI_FJORDS_NATIONAL_PARK%2C_ALASKA_--_NORTHWEST_GLACIER.jpg" },
  { name: "Kings Canyon", state: "California", description: "Home to the General Grant Tree—the world's second-largest measured tree—and the stunning Kings River canyon, one of the deepest in North America.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/KingsCanyonNP.JPG/400px-KingsCanyonNP.JPG" },
  { name: "Kobuk Valley", state: "Alaska", description: "Entirely above the Arctic Circle, this park features the Great Kobuk Sand Dunes and protects caribou migration routes through the remote Brooks Range.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Wetlands_along_the_Kobuk_River_%288029770162%29.jpg/400px-Wetlands_along_the_Kobuk_River_%288029770162%29.jpg" },
  { name: "Lake Clark", state: "Alaska", description: "A vast, wild landscape of volcanoes, glaciers, wild rivers, and waterfalls in the heart of the Aleutian Range, home to abundant brown bears and salmon runs.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Lake_Clark_National_Park.jpg/400px-Lake_Clark_National_Park.jpg" },
  { name: "Lassen Volcanic", state: "California", description: "Home to Lassen Peak, the largest plug dome volcano in the world, with all four types of volcanoes, boiling mudpots, fumaroles, and steaming ground.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Lassen_Peak_and_Lake_Helen.jpg/400px-Lassen_Peak_and_Lake_Helen.jpg" },
  { name: "Mammoth Cave", state: "Kentucky", description: "Protecting the world's longest known cave system with over 400 miles of explored passages, along with a diverse surface ecosystem of rivers and forests.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Mammoth_Cave_National_Park_007.jpg/400px-Mammoth_Cave_National_Park_007.jpg" },
  { name: "Mesa Verde", state: "Colorado", description: "A UNESCO World Heritage Site preserving nearly 5,000 archaeological sites including 600 cliff dwellings, the best-preserved Ancestral Puebloan ruins in the US.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Mesa_Verde_National_Park_Cliff_Palace_2006_09_12.jpg/400px-Mesa_Verde_National_Park_Cliff_Palace_2006_09_12.jpg" },
  { name: "Mount Rainier", state: "Washington", description: "Dominated by the 14,411-foot active stratovolcano with 25 major glaciers, subalpine wildflower meadows, and old-growth forests of the Pacific Northwest.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Mount_Rainier_from_above_Myrtle_Falls_in_August.JPG/400px-Mount_Rainier_from_above_Myrtle_Falls_in_August.JPG" },
  { name: "New River Gorge", state: "West Virginia", description: "The newest national park protects 53 miles of the New River, one of the oldest rivers on the continent, with world-class whitewater rafting and rock climbing.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/New_River_Gorge_Bridge.jpg/400px-New_River_Gorge_Bridge.jpg" },
  { name: "North Cascades", state: "Washington", description: "Known as the American Alps, this park features jagged peaks, over 300 glaciers, pristine alpine lakes, and dense old-growth forests in the Pacific Northwest.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Cascade_Pass.jpg/400px-Cascade_Pass.jpg" },
  { name: "Olympic", state: "Washington", description: "Three distinct ecosystems in one park: glacier-capped mountains, old-growth temperate rainforest, and over 70 miles of wild Pacific coastline.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Cedar_Creek_Abbey_Island_Ruby_Beach.jpg/400px-Cedar_Creek_Abbey_Island_Ruby_Beach.jpg" },
  { name: "Petrified Forest", state: "Arizona", description: "Famous for its large deposits of petrified wood over 200 million years old, this park also features the colorful badlands of the Painted Desert.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Jasper_Forest_at_Petrified_Forest_NP_in_AZ_12.jpg/400px-Jasper_Forest_at_Petrified_Forest_NP_in_AZ_12.jpg" },
  { name: "Pinnacles", state: "California", description: "Formed by an ancient volcano, this park features dramatic rock spires, talus caves with resident bat colonies, and is one of the few release sites for California condors.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Pinnacles_National_Park.jpg/400px-Pinnacles_National_Park.jpg" },
  { name: "Redwood", state: "California", description: "Home to the tallest trees on Earth—coast redwoods reaching over 370 feet—along with prairies, oak woodlands, wild rivers, and 40 miles of pristine coastline.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Redwood_National_Park%2C_fog_in_the_forest.jpg/400px-Redwood_National_Park%2C_fog_in_the_forest.jpg" },
  { name: "Rocky Mountain", state: "Colorado", description: "Majestic mountain peaks, alpine lakes, and diverse wildlife along the Continental Divide, with Trail Ridge Road reaching 12,183 feet above sea level.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Bierstadt_Lake%2C_Rocky_Mountain_National_Park%2C_USA.jpg/400px-Bierstadt_Lake%2C_Rocky_Mountain_National_Park%2C_USA.jpg" },
  { name: "Saguaro", state: "Arizona", description: "Protecting giant saguaro cacti—the largest in the US—and the surrounding Sonoran Desert ecosystem with its unique plants and animals.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Saguaronationalparl17102008.jpg/400px-Saguaronationalparl17102008.jpg" },
  { name: "Sequoia", state: "California", description: "Home to the General Sherman tree, the world's largest tree by volume, along with over 8,000 other giant sequoias, deep canyons, and Mount Whitney.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Sequoia_National_Park%2C_photo_by_Reeve_Bruner%2C_2016.jpg/400px-Sequoia_National_Park%2C_photo_by_Reeve_Bruner%2C_2016.jpg" },
  { name: "Shenandoah", state: "Virginia", description: "The Blue Ridge Mountains are traversed by Skyline Drive and the Appalachian Trail, with cascading waterfalls, panoramic views, and quiet wooded hollows.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Early_Fall_at_Dark_Hollow_Falls_%2822028259442%29.jpg/400px-Early_Fall_at_Dark_Hollow_Falls_%2822028259442%29.jpg" },
  { name: "Theodore Roosevelt", state: "North Dakota", description: "Comprising three geographically separated areas of the North Dakota Badlands, this park memorializes President Roosevelt's conservation legacy.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/View_of_Theodore_Roosevelt_National_Park.jpg/400px-View_of_Theodore_Roosevelt_National_Park.jpg" },
  { name: "Virgin Islands", state: "US Virgin Islands", description: "Covering over half of Saint John island, this park features pristine beaches, tropical forests, historic plantation ruins, and vibrant coral reefs.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/St_John_Trunk_Bay_1.jpg/400px-St_John_Trunk_Bay_1.jpg" },
  { name: "Voyageurs", state: "Minnesota", description: "A network of interconnected waterways forming a water-based park, preserving the historic canoe routes of the French-Canadian fur traders (voyageurs).", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Voyageurs_National_Park.jpg/400px-Voyageurs_National_Park.jpg" },
  { name: "White Sands", state: "New Mexico", description: "The world's largest gypsum dune field, with brilliant white sand dunes covering 275 square miles of desert, creating a surreal landscape.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/White_Sands_New_Mexico_USA.jpg/400px-White_Sands_New_Mexico_USA.jpg" },
  { name: "Wind Cave", state: "South Dakota", description: "One of the longest and most complex caves in the world, with rare boxwork formations, above a mixed-grass prairie home to bison, elk, and prairie dogs.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Skyway_Lake%2C_stalactites%2C_Wind_Cave.jpg/400px-Skyway_Lake%2C_stalactites%2C_Wind_Cave.jpg" },
  { name: "Wrangell-St. Elias", state: "Alaska", description: "The largest national park in the US at over 13 million acres, with the convergence of four major mountain ranges, 9 of the 16 highest US peaks, and abundant glaciers.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Guyot_Hills%2C_Icy_Bay%2C_and_Mount_St._Elias_%2821601563492%29.jpg/400px-Guyot_Hills%2C_Icy_Bay%2C_and_Mount_St._Elias_%2821601563492%29.jpg" },
  { name: "Yellowstone", state: "Wyoming/Montana/Idaho", description: "The world's first national park, famous for its geothermal features including Old Faithful geyser and Grand Prismatic Spring, with abundant wildlife and dramatic canyons.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Grand_Prismatic_Spring_2013.jpg/400px-Grand_Prismatic_Spring_2013.jpg" },
  { name: "Yosemite", state: "California", description: "Known for its towering granite cliffs, waterfalls, giant sequoia groves, and the iconic Half Dome and El Capitan formations in a glacier-carved valley.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Half_Dome_from_Glacier_Point%2C_Yosemite_NP_-_Diliff.jpg/400px-Half_Dome_from_Glacier_Point%2C_Yosemite_NP_-_Diliff.jpg" },
  { name: "Zion", state: "Utah", description: "A dramatic landscape of steep red cliffs and narrow canyons, with the Virgin River cutting through towering sandstone walls up to 2,000 feet high.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zion_angels_landing_view.jpg/400px-Zion_angels_landing_view.jpg" },
];

export async function seedParks() {
  try {
    const count = await storage.getParkCount();
    if (count > 0) {
      log(`Database already has ${count} parks, skipping seed`);
      return;
    }

    log("Seeding parks data...");
    for (const park of PARKS_DATA) {
      await storage.createPark(park);
    }
    log(`Seeded ${PARKS_DATA.length} parks successfully`);
  } catch (error) {
    log(`Error seeding parks: ${error}`);
  }
}
